#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using the while loop,
# but for the 9th iteration, displays Best School and then Hi on a new line

counter=1

while [ $counter -le 10 ]
do
    echo "Best School"
        if [ $counter -eq 9 ]
        then
            echo "Hi"
	fi
    ((counter++))
done