#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using the while loop,
# but for the 9th iteration, displays Best School and then Hi on a new 


counter=0
while [ $counter -lt 11 ]
do
    if [ $counter -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done

