#!/usr/bin/env bash
# Fix the bug in apache 2
sed -i '/Listen 80 Listen 8080' /etc/apache2/ports.conf
sed -i '/VirtualHost>/a <VirtualHost *:80 *:8888>\nServerAdmin webmaster@localhost\nDocumentRoot /var/www/html\n</VirtualHost>' /etc/apache2/sites-available/000-default.conf
sudo apache2ctl restart